[programs.localnet]
account = "4m74PiSDGJp4QFmcU2b2KDUBNPuLMSjaD9oFi9ccK8KW"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/zyjliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js"

[test]
startup_wait = 100000